version: '3.8'
services:
  clima-app:
    build: .
    image: clima-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: clima
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: